package entidades;
// Generated Jun 27, 2019 5:12:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Boleta generated by hbm2java
 */
@Entity
@Table(name="boleta"
    ,catalog="comercio"
)
public class Boleta  implements java.io.Serializable {


     private Integer id;
     private Date fechaRegistro;
     private Set productos = new HashSet(0);

    public Boleta() {
    }

    public Boleta(Date fechaRegistro, Set productos) {
       this.fechaRegistro = fechaRegistro;
       this.productos = productos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaRegistro", length=19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="producto_has_boleta", catalog="comercio", joinColumns = { 
        @JoinColumn(name="boleta_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="producto_id", nullable=false, updatable=false) })
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


