package entidades;
// Generated May 12, 2019, 3:12:24 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name="curso"
    ,catalog="colegio"
)
public class Curso  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String docente;
     private String lugar;

    public Curso() {
    }

    public Curso(String nombre, String docente, String lugar) {
       this.nombre = nombre;
       this.docente = docente;
       this.lugar = lugar;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="docente", length=45)
    public String getDocente() {
        return this.docente;
    }
    
    public void setDocente(String docente) {
        this.docente = docente;
    }

    
    @Column(name="lugar", length=45)
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }




}


