package entidades;
// Generated Jun 27, 2019 5:12:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="comercio"
)
public class Producto  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria;
     private String nombre;
     private Double precio;
     private Integer stock;
     private Set boletas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Categoria categoria) {
        this.categoria = categoria;
    }
    public Producto(Categoria categoria, String nombre, Double precio, Integer stock, Set boletas) {
       this.categoria = categoria;
       this.nombre = nombre;
       this.precio = precio;
       this.stock = stock;
       this.boletas = boletas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="categoria", nullable=false)
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="precio", precision=22, scale=0)
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    
    @Column(name="stock")
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="producto_has_boleta", catalog="comercio", joinColumns = { 
        @JoinColumn(name="producto_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="boleta_id", nullable=false, updatable=false) })
    public Set getBoletas() {
        return this.boletas;
    }
    
    public void setBoletas(Set boletas) {
        this.boletas = boletas;
    }




}


